
version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: 10xdevai
    volumes:
      - .:/srv/jekyll
    ports:
      - "4001:4000"
    command: >
      sh -c "bundle install &&
             bundle exec jekyll serve -s docs --watch --drafts --livereload --host 0.0.0.0"
    stdin_open: true
    tty: true
